### ISSUE TITLE
Any way to point the plugin to a standalone JRE?

### ISSUE THREAD

**Issue by PawelJagus** [heroku/plugin-java#2]
I don't have a possibility to install JRE globally on the system I am working on, instead I use a standalone JRE extracted from a .tar.gz available on www.java.com.

Unfortunately even if I create an alias and then register it to be available in non-interactive shells, I am still getting the following exception while deploying.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

It would be nice to be able to point the plugin to the standalone version of JRE.

**Comment by Malax** [comment]
Hello @PawelJagus, this is an old issue and probably not relevant to you anymore. I will close it, but feel free to re-open anytime!
